name: Startup-Time

on:
    workflow_dispatch:


jobs:
  set-tag:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.branch.outputs.tag }}
    steps:
      - id: branch
        run: if [[ "${GITHUB_REF_NAME}" == "main" ]]; then echo "tag=latest" >> "$GITHUB_OUTPUT"; else echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"; fi
  startup-time:
    runs-on: ubuntu-latest
    needs: set-tag
    container:
      image: docker.io/${{ vars.DOCKERHUB_USERNAME }}/mhpg:${{needs.set-tag.outputs.docker_tag}}
    steps:
      - name: Run Test
        run: |
          cd /code
          touch startup.json
          ./mhpgeez startup-time -v
      - name: Store JSON file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: startup.json
          path: /code/startup.json
          retention-days: 2