name: Tests

on:
  workflow_dispatch:
    inputs:
      testcase:
        type: choice
        required: true
        description: Select the test case you would like to generate
        options: 
        - 1 [LetExample]
        - 2 [LetAddExample]
        - 3 [NestedFunction]
        - 4 [DataSimpleDeclarations]
        - 5 [LongIdentifier]
        - 6 [Fields_DependentRecordModule]
        - 7 [ChainDef_DependentRecordModule]
        - 8 [Parameters_DependentRecordModule]
        - 9 [NewlineFile]
        - 10 [Fields_NonDependentRecordModule]
        - 11 [ChainDefFields_NonDependentRecordModule]
        - 12 [Constructors_Datatypes]
        - 13 [Parameters_Datatypes]
        - 14 [FirstLast_VariableModule]
        - 15 [DeepDependency_VariableModule]
        - 16 [DataImplicitIndices]
        - 17 [SingleLongLine]
        - 18 [ConstructorsParameters_Datatypes]
        - 19 [IndicesConstructors_Datatypes]
        - 20 [IndicesParameters_Datatypes]
        - 21 [Pattern_Matching_Datatypes]
      size:
        description: Select the size of the test case (must be an integer value between 0 and 20)
        required: true

jobs:
  workflow-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Adding workflow inputs to job summary
        run: |
            testcase=$(echo '${{ github.event.inputs.testcase }}' | grep -oP '\[\K[^\]]+')
            {
            echo "### Workflow Inputs"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Testcase            | $testcase |"
            echo "| Size          | ${{ github.event.inputs.size }} |"
            } >> $GITHUB_STEP_SUMMARY
  generate-test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/${{ vars.DOCKERHUB_USERNAME }}/mhpg:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Run Test
        run: |
          if ! [[ "${{ github.event.inputs.size }}" =~ ^[0-9]+$ ]] || [ "${{ github.event.inputs.size }}" -le -1 ] || [ "${{ github.event.inputs.size }}" -ge 21 ]; then echo "Please input a value between 0 and 20"; exit 1; fi
          cd translators
          ghc -o translators main.hs
          chmod +x translators
          mkdir out
          testcase=$(echo ${{ github.event.inputs.testcase }} | grep -o '^[0-9]\+')
          printf '%s\n%s\n' "$testcase" ${{ github.event.inputs.size }} | ./translators
          cd out 
          GREEN='\033[0;32m'
          file_name=$(echo '${{ github.event.inputs.testcase }}' | grep -oP '\[\K[^\]]+')
          echo -e "${GREEN} Coq $file_name File Contents:"
          cat "$file_name.v"
          echo -e "\n${GREEN} Coq $file_name Type Check Output:"
          coqc "$file_name.v"
          echo -e "\n${GREEN} Lean $file_name File Contents:"
          cat "$file_name.lean"
          echo -e "${GREEN} Lean $file_name Type Check Output:"
          lean "$file_name.lean" 
          echo -e "\n${GREEN} Idris $file_name File Contents:"
          cat "$file_name.idr"
          echo -e "${GREEN} Idris $file_name Type Check Output:"
          idris2 --check "$file_name.idr"
          echo -e "\n${GREEN} Agda $file_name File Contents:"
          cat "./$file_name.agda"
          echo -e "${GREEN} Agda $file_name Type Check Output:"
          agda "./$file_name.agda"
        shell: bash
      - name: Store generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./translators/out
          retention-days: 1
